package by.epam.jwd.controller.command.impl.ajax;

public enum AjaxCommandName {
	GET_SPECIALTIES_BY_FACULTY,
	GET_ALL_FACULTIES,
	GET_ALL_SPECIALTIES,
	GET_ALL_USERS,
	GET_ALL_PLANS,
	GET_ALL_TYPES,
	GET_ALL_MATRICULANTS,
	GET_ALL_SUBJECTS,
	GET_ALL_MATRICULANTS_BY_SPECIALTY,
	GET_ALL_MATRICULANTS_BY_PROPERTY,
	GET_ALL_SPECIALTY_HAS_SUBJECT,
	WRONG_METHOD
}
