package by.epam.jwd.controller.command.impl.front;

public enum CommandName {
	REGISTR,
	SIGN_OUT,
	SIGN_IN,
	SHOW_USER_DETAIL,
	SHOW_ADMIN_PANEL,
	SHOW_USER_DATA,
	CHANGE_LOCALE,
	CHANGE_USER_DETAIL,
	CHANGE_USER_PASSWORD,
	SHOW_ALL_SPECIALTIES,
	SHOW_TABLE_SPECIALTIES,
	SHOW_SPECIALTY,
	SHOW_MATRICULANT,
	ADD_MATRICULANT,
	BLOCK_USER,
	WRONG_METHOD
}
