package by.epam.jwd.controller.command.impl.ajax;

public enum AjaxCommandName {
	GET_SPECIALTIES_BY_FACULTY,
	GET_ALL_FACULTIES,
	GET_ALL_SPECIALTIES,
	GET_ALL_USERS,
	GET_ALL_PLANS,
	GET_ALL_TYPES,
	GET_ALL_MATRICULANTS,
	WRONG_METHOD
}
